// Generated by artifacts/gen-reconcile-fixture.mjs. Sanitized
// equality-preserving token fixture of the real crash-shape reconcile
// input: session 40ebe83d recovered checkpoint (72 items) vs the
// crash-time loaded history projection (78 items). Do not edit by
// hand; regenerate from the real data if the shape needs updating.
import type { SessionTranscriptItem } from '../../shared/bridgeMessages';

export const realShapeRecovered: readonly SessionTranscriptItem[] =
  [
    {
      "id": "id1",
      "kind": "user",
      "text": "text1",
      "messageId": "mid1"
    },
    {
      "id": "id2",
      "kind": "assistant",
      "turnId": "turn1",
      "text": "text2"
    },
    {
      "id": "id3",
      "kind": "user",
      "text": "text3",
      "messageId": "mid2"
    },
    {
      "id": "id4",
      "kind": "user",
      "text": "text3",
      "messageId": "mid3"
    },
    {
      "id": "id5",
      "kind": "thinking",
      "turnId": "turn2",
      "text": "text4",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id6",
      "kind": "assistant",
      "turnId": "turn2",
      "text": "text5"
    },
    {
      "id": "id7",
      "kind": "user",
      "text": "text6",
      "messageId": "mid4"
    },
    {
      "id": "id8",
      "kind": "thinking",
      "turnId": "turn3",
      "text": "text7",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id9",
      "kind": "tool",
      "turnId": "turn3",
      "toolUseId": "tu1",
      "toolName": "Glob",
      "action": "action1",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id10",
      "kind": "tool",
      "turnId": "turn4",
      "toolUseId": "tu2",
      "toolName": "Glob",
      "action": "action1",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id11",
      "kind": "tool",
      "turnId": "turn5",
      "toolUseId": "tu3",
      "toolName": "Glob",
      "action": "action1",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id12",
      "kind": "thinking",
      "turnId": "turn6",
      "text": "text8",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id13",
      "kind": "assistant",
      "turnId": "turn6",
      "text": "text9"
    },
    {
      "id": "id14",
      "kind": "tool",
      "turnId": "turn6",
      "toolUseId": "tu4",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id15",
      "kind": "tool",
      "turnId": "turn6",
      "toolUseId": "tu5",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id16",
      "kind": "tool",
      "turnId": "turn6",
      "toolUseId": "tu6",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id17",
      "kind": "thinking",
      "turnId": "turn7",
      "text": "text10",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id18",
      "kind": "assistant",
      "turnId": "turn7",
      "text": "text11"
    },
    {
      "id": "id19",
      "kind": "user",
      "text": "text12",
      "messageId": "mid5"
    },
    {
      "id": "id20",
      "kind": "thinking",
      "turnId": "turn8",
      "text": "text13",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id21",
      "kind": "tool",
      "turnId": "turn8",
      "toolUseId": "tu7",
      "toolName": "Execute",
      "action": "action3",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id22",
      "kind": "assistant",
      "turnId": "turn9",
      "text": "text14"
    },
    {
      "id": "id23",
      "kind": "user",
      "text": "text15",
      "messageId": "mid6"
    },
    {
      "id": "id24",
      "kind": "thinking",
      "turnId": "turn10",
      "text": "text16",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id25",
      "kind": "tool",
      "turnId": "turn10",
      "toolUseId": "tu8",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id26",
      "kind": "assistant",
      "turnId": "turn11",
      "text": "text17"
    },
    {
      "id": "id27",
      "kind": "user",
      "text": "text18",
      "messageId": "mid7"
    },
    {
      "id": "id28",
      "kind": "thinking",
      "turnId": "turn12",
      "text": "text19",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id29",
      "kind": "tool",
      "turnId": "turn12",
      "toolUseId": "tu9",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id30",
      "kind": "thinking",
      "turnId": "turn13",
      "text": "text20",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id31",
      "kind": "tool",
      "turnId": "turn13",
      "toolUseId": "tu10",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id32",
      "kind": "thinking",
      "turnId": "turn14",
      "text": "text21",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id33",
      "kind": "assistant",
      "turnId": "turn14",
      "text": "text22"
    },
    {
      "id": "id34",
      "kind": "user",
      "text": "text23",
      "messageId": "mid8"
    },
    {
      "id": "id35",
      "kind": "thinking",
      "turnId": "turn15",
      "text": "text24",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id36",
      "kind": "tool",
      "turnId": "turn15",
      "toolUseId": "tu11",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id37",
      "kind": "thinking",
      "turnId": "turn16",
      "text": "text25",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id38",
      "kind": "assistant",
      "turnId": "turn16",
      "text": "text26"
    },
    {
      "id": "id39",
      "kind": "user",
      "text": "text27",
      "messageId": "mid9"
    },
    {
      "id": "id40",
      "kind": "thinking",
      "turnId": "turn17",
      "text": "text28",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id41",
      "kind": "assistant",
      "turnId": "turn17",
      "text": "text29"
    },
    {
      "id": "id42",
      "kind": "user",
      "text": "text30",
      "messageId": "mid10"
    },
    {
      "id": "id43",
      "kind": "thinking",
      "turnId": "turn18",
      "text": "text31",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id44",
      "kind": "assistant",
      "turnId": "turn18",
      "text": "text32"
    },
    {
      "id": "id45",
      "kind": "tool",
      "turnId": "turn18",
      "toolUseId": "tu12",
      "toolName": "AskUser",
      "action": "action4",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id46",
      "kind": "thinking",
      "turnId": "turn19",
      "text": "text33",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id47",
      "kind": "assistant",
      "turnId": "turn19",
      "text": "text34"
    },
    {
      "id": "id48",
      "kind": "user",
      "text": "text35",
      "messageId": "mid11"
    },
    {
      "id": "id49",
      "kind": "thinking",
      "turnId": "turn20",
      "text": "text36",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id50",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu13",
      "toolName": "Skill",
      "action": "action5",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id51",
      "kind": "thinking",
      "turnId": "turn20",
      "text": "text37",
      "status": "complete",
      "truncated": true
    },
    {
      "id": "id52",
      "kind": "assistant",
      "turnId": "turn20",
      "text": "text38"
    },
    {
      "id": "id53",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu14",
      "toolName": "Create",
      "action": "action6",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id54",
      "kind": "assistant",
      "turnId": "turn20",
      "text": "text39"
    },
    {
      "id": "id55",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu15",
      "toolName": "ExitSpecMode",
      "action": "action7",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id56",
      "kind": "assistant",
      "turnId": "turn20",
      "text": "text40"
    },
    {
      "id": "id57",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu16",
      "toolName": "Create",
      "action": "action6",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id58",
      "kind": "assistant",
      "turnId": "turn20",
      "text": "text41"
    },
    {
      "id": "id59",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu17",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 1,
      "latestUpdateKind": "status"
    },
    {
      "id": "id60",
      "kind": "tool",
      "turnId": "turn20",
      "toolUseId": "tu18",
      "toolName": "openFile",
      "action": "action8",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id61",
      "kind": "assistant",
      "turnId": "turn20",
      "text": "text42"
    },
    {
      "id": "id62",
      "kind": "user",
      "text": "text43",
      "messageId": "mid12"
    },
    {
      "id": "id63",
      "kind": "thinking",
      "turnId": "turn21",
      "text": "text44",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id64",
      "kind": "assistant",
      "turnId": "turn21",
      "text": "text45"
    },
    {
      "id": "id65",
      "kind": "tool",
      "turnId": "turn21",
      "toolUseId": "tu19",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 2,
      "latestUpdateKind": "status"
    },
    {
      "id": "id66",
      "kind": "thinking",
      "turnId": "turn21",
      "text": "text46",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id67",
      "kind": "assistant",
      "turnId": "turn21",
      "text": "text47"
    },
    {
      "id": "id68",
      "kind": "tool",
      "turnId": "turn21",
      "toolUseId": "tu20",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 2,
      "latestUpdateKind": "status"
    },
    {
      "id": "id69",
      "kind": "thinking",
      "turnId": "turn21",
      "text": "text48",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id70",
      "kind": "assistant",
      "turnId": "turn21",
      "text": "text49"
    },
    {
      "id": "id71",
      "kind": "tool",
      "turnId": "turn21",
      "toolUseId": "tu21",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 2,
      "latestUpdateKind": "status"
    },
    {
      "id": "id72",
      "kind": "assistant",
      "turnId": "turn21",
      "text": "text50"
    }
  ];

export const realShapeLoaded: readonly SessionTranscriptItem[] =
  [
    {
      "id": "id73",
      "kind": "user",
      "text": "text3",
      "messageId": "mid3"
    },
    {
      "id": "id74",
      "kind": "thinking",
      "turnId": "turn22",
      "text": "text4",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id75",
      "kind": "assistant",
      "turnId": "turn22",
      "text": "text5"
    },
    {
      "id": "id76",
      "kind": "user",
      "text": "text6",
      "messageId": "mid4"
    },
    {
      "id": "id77",
      "kind": "thinking",
      "turnId": "turn23",
      "text": "text7",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id78",
      "kind": "tool",
      "turnId": "turn23",
      "toolUseId": "tu22",
      "toolName": "Glob",
      "action": "action1",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id79",
      "kind": "tool",
      "turnId": "turn24",
      "toolUseId": "tu23",
      "toolName": "Glob",
      "action": "action1",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id80",
      "kind": "tool",
      "turnId": "turn25",
      "toolUseId": "tu24",
      "toolName": "Glob",
      "action": "action1",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id81",
      "kind": "thinking",
      "turnId": "turn26",
      "text": "text8",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id82",
      "kind": "assistant",
      "turnId": "turn26",
      "text": "text9"
    },
    {
      "id": "id83",
      "kind": "tool",
      "turnId": "turn26",
      "toolUseId": "tu25",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id84",
      "kind": "tool",
      "turnId": "turn26",
      "toolUseId": "tu26",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id85",
      "kind": "tool",
      "turnId": "turn26",
      "toolUseId": "tu27",
      "toolName": "Read",
      "action": "action2",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id86",
      "kind": "thinking",
      "turnId": "turn27",
      "text": "text10",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id87",
      "kind": "assistant",
      "turnId": "turn27",
      "text": "text11"
    },
    {
      "id": "id88",
      "kind": "user",
      "text": "text12",
      "messageId": "mid5"
    },
    {
      "id": "id89",
      "kind": "thinking",
      "turnId": "turn28",
      "text": "text13",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id90",
      "kind": "tool",
      "turnId": "turn28",
      "toolUseId": "tu28",
      "toolName": "Execute",
      "action": "action3",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id91",
      "kind": "assistant",
      "turnId": "turn29",
      "text": "text14"
    },
    {
      "id": "id92",
      "kind": "user",
      "text": "text15",
      "messageId": "mid6"
    },
    {
      "id": "id93",
      "kind": "thinking",
      "turnId": "turn30",
      "text": "text16",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id94",
      "kind": "tool",
      "turnId": "turn30",
      "toolUseId": "tu29",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id95",
      "kind": "assistant",
      "turnId": "turn31",
      "text": "text17"
    },
    {
      "id": "id96",
      "kind": "user",
      "text": "text18",
      "messageId": "mid7"
    },
    {
      "id": "id97",
      "kind": "thinking",
      "turnId": "turn32",
      "text": "text19",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id98",
      "kind": "tool",
      "turnId": "turn32",
      "toolUseId": "tu30",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id99",
      "kind": "thinking",
      "turnId": "turn33",
      "text": "text20",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id100",
      "kind": "tool",
      "turnId": "turn33",
      "toolUseId": "tu31",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id101",
      "kind": "thinking",
      "turnId": "turn34",
      "text": "text21",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id102",
      "kind": "assistant",
      "turnId": "turn34",
      "text": "text22"
    },
    {
      "id": "id103",
      "kind": "user",
      "text": "text23",
      "messageId": "mid8"
    },
    {
      "id": "id104",
      "kind": "thinking",
      "turnId": "turn35",
      "text": "text24",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id105",
      "kind": "tool",
      "turnId": "turn35",
      "toolUseId": "tu32",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id106",
      "kind": "thinking",
      "turnId": "turn36",
      "text": "text25",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id107",
      "kind": "assistant",
      "turnId": "turn36",
      "text": "text26"
    },
    {
      "id": "id108",
      "kind": "user",
      "text": "text27",
      "messageId": "mid9"
    },
    {
      "id": "id109",
      "kind": "thinking",
      "turnId": "turn37",
      "text": "text28",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id110",
      "kind": "assistant",
      "turnId": "turn37",
      "text": "text29"
    },
    {
      "id": "id111",
      "kind": "user",
      "text": "text30",
      "messageId": "mid10"
    },
    {
      "id": "id112",
      "kind": "thinking",
      "turnId": "turn38",
      "text": "text31",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id113",
      "kind": "assistant",
      "turnId": "turn38",
      "text": "text32"
    },
    {
      "id": "id114",
      "kind": "tool",
      "turnId": "turn38",
      "toolUseId": "tu33",
      "toolName": "AskUser",
      "action": "action4",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id115",
      "kind": "thinking",
      "turnId": "turn39",
      "text": "text33",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id116",
      "kind": "assistant",
      "turnId": "turn39",
      "text": "text34"
    },
    {
      "id": "id117",
      "kind": "user",
      "text": "text35",
      "messageId": "mid11"
    },
    {
      "id": "id118",
      "kind": "thinking",
      "turnId": "turn40",
      "text": "text36",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id119",
      "kind": "tool",
      "turnId": "turn40",
      "toolUseId": "tu34",
      "toolName": "Skill",
      "action": "action5",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id120",
      "kind": "thinking",
      "turnId": "turn41",
      "text": "text51",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id121",
      "kind": "assistant",
      "turnId": "turn41",
      "text": "text38"
    },
    {
      "id": "id122",
      "kind": "tool",
      "turnId": "turn41",
      "toolUseId": "tu35",
      "toolName": "Create",
      "action": "action6",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id123",
      "kind": "changes",
      "turnId": "turn41",
      "files": [
        {
          "path": "file1",
          "additions": null,
          "deletions": null
        }
      ]
    },
    {
      "id": "id124",
      "kind": "thinking",
      "turnId": "turn42",
      "text": "text52",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id125",
      "kind": "assistant",
      "turnId": "turn42",
      "text": "text39"
    },
    {
      "id": "id126",
      "kind": "tool",
      "turnId": "turn42",
      "toolUseId": "tu36",
      "toolName": "ExitSpecMode",
      "action": "action7",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id127",
      "kind": "thinking",
      "turnId": "turn43",
      "text": "text53",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id128",
      "kind": "assistant",
      "turnId": "turn43",
      "text": "text40"
    },
    {
      "id": "id129",
      "kind": "tool",
      "turnId": "turn43",
      "toolUseId": "tu37",
      "toolName": "Create",
      "action": "action6",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id130",
      "kind": "changes",
      "turnId": "turn43",
      "files": [
        {
          "path": "file1",
          "additions": null,
          "deletions": null
        }
      ]
    },
    {
      "id": "id131",
      "kind": "thinking",
      "turnId": "turn44",
      "text": "text54",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id132",
      "kind": "assistant",
      "turnId": "turn44",
      "text": "text41"
    },
    {
      "id": "id133",
      "kind": "tool",
      "turnId": "turn44",
      "toolUseId": "tu38",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id134",
      "kind": "tool",
      "turnId": "turn44",
      "toolUseId": "tu39",
      "toolName": "openFile",
      "action": "action8",
      "status": "failed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id135",
      "kind": "thinking",
      "turnId": "turn45",
      "text": "text55",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id136",
      "kind": "assistant",
      "turnId": "turn45",
      "text": "text42"
    },
    {
      "id": "id137",
      "kind": "user",
      "text": "text43",
      "messageId": "mid12"
    },
    {
      "id": "id138",
      "kind": "thinking",
      "turnId": "turn46",
      "text": "text44",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id139",
      "kind": "assistant",
      "turnId": "turn46",
      "text": "text45"
    },
    {
      "id": "id140",
      "kind": "tool",
      "turnId": "turn46",
      "toolUseId": "tu40",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id141",
      "kind": "thinking",
      "turnId": "turn47",
      "text": "text46",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id142",
      "kind": "assistant",
      "turnId": "turn47",
      "text": "text47"
    },
    {
      "id": "id143",
      "kind": "tool",
      "turnId": "turn47",
      "toolUseId": "tu41",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id144",
      "kind": "thinking",
      "turnId": "turn48",
      "text": "text48",
      "status": "complete",
      "truncated": false
    },
    {
      "id": "id145",
      "kind": "assistant",
      "turnId": "turn48",
      "text": "text49"
    },
    {
      "id": "id146",
      "kind": "tool",
      "turnId": "turn48",
      "toolUseId": "tu42",
      "toolName": "Execute",
      "action": "action3",
      "status": "completed",
      "progressCount": 0,
      "latestUpdateKind": null
    },
    {
      "id": "id147",
      "kind": "assistant",
      "turnId": "turn49",
      "text": "text50"
    },
    {
      "id": "id148",
      "kind": "user",
      "text": "text1",
      "messageId": "mid13"
    },
    {
      "id": "id149",
      "kind": "assistant",
      "turnId": "turn50",
      "text": "text56"
    },
    {
      "id": "id150",
      "kind": "user",
      "text": "text57",
      "messageId": "mid14"
    }
  ];
