import { useState, type ReactElement } from 'react';

import { MediaLightbox, type MediaSize } from './Lightbox';
import {
  IMAGE_MEDIA_TYPES,
  MAX_IMAGE_DATA_LENGTH,
  type ImageMediaType,
} from '../../shared/bridgeMessages';

interface TranscriptImageData {
  readonly mediaType: ImageMediaType;
  readonly data: string;
  readonly generated: boolean;
  readonly byteLength: number;
}

const BASE64_PATTERN = /^[A-Za-z0-9+/]*={0,2}$/;

/**
 * Reads a `droid-image` data part at the render boundary. The data URI
 * is assembled here from the whitelisted media type and the validated
 * base64 payload; transported strings are never used as a URI directly.
 */
function readTranscriptImage(
  value: unknown,
): TranscriptImageData | undefined {
  if (typeof value !== 'object' || value === null) {
    return undefined;
  }
  const record = value as Record<string, unknown>;
  const mediaType = record.mediaType;
  const data = record.data;
  const byteLength = record.byteLength;
  if (
    typeof mediaType !== 'string' ||
    !(IMAGE_MEDIA_TYPES as readonly string[]).includes(mediaType) ||
    typeof data !== 'string' ||
    data.length > MAX_IMAGE_DATA_LENGTH ||
    !BASE64_PATTERN.test(data) ||
    !Number.isSafeInteger(byteLength) ||
    (byteLength as number) < 0
  ) {
    return undefined;
  }
  return {
    mediaType: mediaType as ImageMediaType,
    data,
    generated: record.generated === true,
    byteLength: byteLength as number,
  };
}

function formatBytes(byteLength: number): string {
  if (byteLength >= 1_048_576) {
    return `${(byteLength / 1_048_576).toFixed(1)} MB`;
  }
  if (byteLength >= 1_024) {
    return `${Math.round(byteLength / 1_024)} KB`;
  }
  return `${byteLength} B`;
}

/**
 * One inline transcript image: a height-bounded thumbnail that opens a
 * panel-local lightbox, or a placeholder row when the bytes were
 * dropped (oversized for the Bridge or evicted by the session image
 * budget).
 */
export function TranscriptImage({
  data,
}: {
  readonly data: unknown;
}): ReactElement | null {
  const [expanded, setExpanded] = useState(false);

  const image = readTranscriptImage(data);
  if (image === undefined) {
    return null;
  }
  if (image.data.length === 0) {
    return (
      // Spans with block/flex display: markdown can place an image
      // reference inside a <p>, where a div nests invalidly.
      <span className="dvx-image-placeholder" role="note">
        Image · {formatBytes(image.byteLength)} (preview unavailable)
      </span>
    );
  }
  const src = `data:${image.mediaType};base64,${image.data}`;
  return (
    <span className="dvx-transcript-image">
      <button
        type="button"
        className="dvx-image-thumb-button"
        title="Click to enlarge"
        aria-label={`Enlarge image (${formatBytes(image.byteLength)})`}
        onClick={(event) => {
          event.stopPropagation();
          setExpanded(true);
        }}
      >
        <img
          className="dvx-image-thumb"
          src={src}
          alt={
            image.generated
              ? 'Image generated by Droid'
              : 'Image attachment'
          }
        />
      </button>
      {image.generated ? (
        <span className="dvx-image-badge">Generated</span>
      ) : null}
      {expanded ? (
        <ImageLightbox src={src} onClose={() => setExpanded(false)} />
      ) : null}
    </span>
  );
}

/**
 * Full-viewport image preview on the shared media lightbox; the image
 * reports its natural resolution on load so `scale` reads directly as
 * a zoom percentage.
 */
export function ImageLightbox({
  src,
  onClose,
}: {
  readonly src: string;
  readonly onClose: () => void;
}): ReactElement {
  const [size, setSize] = useState<MediaSize | null>(null);
  return (
    <MediaLightbox
      label="Image preview"
      contentSize={size}
      onClose={onClose}
    >
      <img
        className="dvx-lightbox-image"
        src={src}
        alt="Full size image"
        draggable={false}
        onLoad={(event) => {
          const img = event.currentTarget;
          if (img.naturalWidth > 0 && img.naturalHeight > 0) {
            setSize({
              width: img.naturalWidth,
              height: img.naturalHeight,
            });
          }
        }}
      />
    </MediaLightbox>
  );
}
