import {
  useCallback,
  useEffect,
  useState,
  type ReactElement,
} from 'react';

import {
  IMAGE_MEDIA_TYPES,
  MAX_IMAGE_DATA_LENGTH,
  type ImageMediaType,
} from '../../shared/bridgeMessages';

interface TranscriptImageData {
  readonly mediaType: ImageMediaType;
  readonly data: string;
  readonly generated: boolean;
  readonly byteLength: number;
}

const BASE64_PATTERN = /^[A-Za-z0-9+/]*={0,2}$/;

/**
 * Reads a `droid-image` data part at the render boundary. The data URI
 * is assembled here from the whitelisted media type and the validated
 * base64 payload; transported strings are never used as a URI directly.
 */
function readTranscriptImage(
  value: unknown,
): TranscriptImageData | undefined {
  if (typeof value !== 'object' || value === null) {
    return undefined;
  }
  const record = value as Record<string, unknown>;
  const mediaType = record.mediaType;
  const data = record.data;
  const byteLength = record.byteLength;
  if (
    typeof mediaType !== 'string' ||
    !(IMAGE_MEDIA_TYPES as readonly string[]).includes(mediaType) ||
    typeof data !== 'string' ||
    data.length > MAX_IMAGE_DATA_LENGTH ||
    !BASE64_PATTERN.test(data) ||
    !Number.isSafeInteger(byteLength) ||
    (byteLength as number) < 0
  ) {
    return undefined;
  }
  return {
    mediaType: mediaType as ImageMediaType,
    data,
    generated: record.generated === true,
    byteLength: byteLength as number,
  };
}

function formatBytes(byteLength: number): string {
  if (byteLength >= 1_048_576) {
    return `${(byteLength / 1_048_576).toFixed(1)} MB`;
  }
  if (byteLength >= 1_024) {
    return `${Math.round(byteLength / 1_024)} KB`;
  }
  return `${byteLength} B`;
}

/**
 * One inline transcript image: a height-bounded thumbnail that opens a
 * panel-local lightbox, or a placeholder row when the bytes were
 * dropped (oversized for the Bridge or evicted by the session image
 * budget).
 */
export function TranscriptImage({
  data,
}: {
  readonly data: unknown;
}): ReactElement | null {
  const [expanded, setExpanded] = useState(false);
  const close = useCallback(() => setExpanded(false), []);
  useEffect(() => {
    if (!expanded) {
      return;
    }
    const onKeyDown = (event: KeyboardEvent): void => {
      if (event.key === 'Escape') {
        event.stopPropagation();
        close();
      }
    };
    window.addEventListener('keydown', onKeyDown, true);
    return () => window.removeEventListener('keydown', onKeyDown, true);
  }, [expanded, close]);

  const image = readTranscriptImage(data);
  if (image === undefined) {
    return null;
  }
  if (image.data.length === 0) {
    return (
      <div className="dvx-image-placeholder" role="note">
        Image · {formatBytes(image.byteLength)} (preview unavailable)
      </div>
    );
  }
  const src = `data:${image.mediaType};base64,${image.data}`;
  return (
    <div className="dvx-transcript-image">
      <button
        type="button"
        className="dvx-image-thumb-button"
        title="Click to enlarge"
        aria-label={`Enlarge image (${formatBytes(image.byteLength)})`}
        onClick={() => setExpanded(true)}
      >
        <img
          className="dvx-image-thumb"
          src={src}
          alt={
            image.generated
              ? 'Image generated by Droid'
              : 'Image attachment'
          }
        />
      </button>
      {image.generated ? (
        <span className="dvx-image-badge">Generated</span>
      ) : null}
      {expanded ? (
        <div
          className="dvx-image-lightbox"
          role="dialog"
          aria-modal="true"
          aria-label="Image preview"
          onClick={close}
        >
          <img
            className="dvx-image-full"
            src={src}
            alt="Full size image"
            onClick={(event) => event.stopPropagation()}
          />
          <button
            type="button"
            className="dvx-image-lightbox-close"
            aria-label="Close image preview"
            onClick={close}
          >
            ✕
          </button>
        </div>
      ) : null}
    </div>
  );
}
